version: '3' # specify docker-compose version

# Define the services/containers to be run
services:
  database: # name of the third service
    image: postgres # specify image to build container from
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"  #specify port forewarding    
  redis: # name of the third service
    image: redis # specify image to build container from
    ports:
      - "6379:6379"  #specify port forewarding
